### PR TITLE
[FIX] use @Aplet123 isSameWeek comparator

### PR DESCRIPTION
**Pull request by r2dev2**
closes #76 

tldr: math for event belong to same week is incorrect, need to fix

### CODE REVIEW

**Review by Arc-blroth — APPROVED** [review]
tested a couple of edge cases and this seems to work so we'll let this algorithm remain victorious for now
gg @Aplet123

**Review by Arc-blroth — CHANGES_REQUESTED** [review]
actually wait
image
`new Date("august 19 2023 11:59:59 PM"),`
it looks like any date _earlier_ than this week is still shown as this week

**Comment by r2dev2** [comment]
> actually wait image `new Date("august 19 2023 11:59:59 PM"),` it looks like any date _earlier_ than this week is still shown as this week

_it was the wrong checkout_

**Review by Arc-blroth — APPROVED** [review]
lgtm

**Pull request merged**
