### PR TITLE
Article buttons

### PR DESCRIPTION
**Pull request by danieltherealyang**
## Summary

Closes #

### CODE REVIEW

**Review by bliutech — CHANGES_REQUESTED** [review]
@danieltherealyang I believe this is still missing some details and features including the implementation of listing all of the blog posts for people to click on. I am also a little bit confused about this implementation since this seems to be a wrapper around ButtonLink and does not actually do any behavioral differences with `next/link`. Could you update the implementation to include listing all of the existing blogs on the `/blog` endpoint? Thanks!

**Review by bliutech — CHANGES_REQUESTED** [review]
The API is not necessary. Could you remove and simply just import a list from all of the blog posts and create a map that displays properly from that?

**Comment by Arc-blroth** [comment]
I've removed the API and replaced the getStaticPaths method with one that directly pulls from the data/ folder. As a side effect, this means that the list of blog posts no longer has to be hardcoded :tada:

**Comment by danieltherealyang** [comment]
wait how is this different from before I made any commits. How do you get an array of the paths from an external component?

**Comment by Arc-blroth** [comment]
> How do you get an array of the paths from an external component

since you wrote that i added some helper code in `utils/BlogPostData.tsx`

**Review by bliutech — APPROVED** [review]
LGTM.

**Pull request merged**
