### PR TITLE
Cyber Icon + Doc Title + README

### PR DESCRIPTION
**Pull request by lness02**
Closes issue #47

Misc changes
- Cyber favicon
- Doc title changed for all pages
- README Updated
- Changed the way the ACM Cyber button redirects to home so that it doesn't reload
- Also slightly readjusted the height of the ACM Cyber word logo thing

### CODE REVIEW

**Comment by errsun** [comment]
lgtm

**Review by bliutech — CHANGES_REQUESTED** [review]
Replace the `useEffect` usage for each pate title with [`next/head`](https://nextjs.org/docs/api-reference/next/head).

**Review by bliutech — CHANGES_REQUESTED** [review]
Adding an image to the README would be nice as well.

**Review by bliutech — APPROVED** [review]
LGTM.

**Pull request merged**
